/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 chips.gltf --transform
Author: Skodvirr (https://sketchfab.com/skodvirr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chips-package-mockup-29627a4fbbd34d88ac874da4530fe113
Title: Chips Package mockup
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/chips-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.67, -0.07, 0.64]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Chipsbag_LP_Bag_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chips-transformed.glb')
