/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 nerdbar.gltf --transform
Author: Daniele Cocchi (https://sketchfab.com/Cocchi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-nerd-bar-low-poly-stylized-32cfbaa5f8344923b2a3378bbc73c2e3
Title: The Nerd Bar - Low Poly Stylized
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/nerdbar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[28.97, 0, 27.34]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-4.84, -8.09, 37]} scale={[16.89, 5.4, 6.13]}>
            <mesh geometry={nodes.pCube1_lambert23_0.geometry} material={materials.lambert23} />
            <mesh geometry={nodes.pCube1_lambert6_0.geometry} material={materials.lambert6} />
            <mesh geometry={nodes.pCube1_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-0.31, 0.44, 16.21]} scale={[12.57, 18.9, 7.46]}>
            <mesh geometry={nodes.pCube3_blinn6_0.geometry} material={materials.blinn6} />
            <mesh geometry={nodes.pCube3_blinn5_0.geometry} material={materials.blinn5} />
          </group>
          <group position={[10.97, 3.41, 13]} rotation={[Math.PI / 2, 0, 0]} scale={[4, 1.39, 4]}>
            <mesh geometry={nodes.pCylinder1_lambert11_0.geometry} material={materials.lambert11} />
            <mesh geometry={nodes.pCylinder1_lambert13_0.geometry} material={materials.lambert13} />
          </group>
          <group position={[-15.56, -10.39, 42]} scale={[1.75, 5.59, 1.75]}>
            <mesh geometry={nodes.pCube10_lambert20_0.geometry} material={materials.lambert20} />
            <mesh geometry={nodes.pCube10_lambert19_0.geometry} material={materials.lambert19} />
          </group>
          <group position={[-13.65, 1.98, 33]} scale={[0.34, 5.91, 0.34]}>
            <mesh geometry={nodes.pCylinder6_lambert7_0.geometry} material={materials.lambert19} />
            <mesh geometry={nodes.pCylinder6_lambert1_0.geometry} material={materials.blinn6} />
            <mesh geometry={nodes.pCylinder6_blinn3_0.geometry} material={materials.blinn3} />
          </group>
          <group position={[-10.41, 6.68, 33]} rotation={[0, 0, Math.PI / 2]} scale={[0.28, 4, 0.28]}>
            <mesh geometry={nodes.pCylinder7_lambert16_0.geometry} material={materials.lambert19} />
            <mesh geometry={nodes.pCylinder7_blinn7_0.geometry} material={materials.blinn7} />
          </group>
          <group position={[-11.87, 6, 25]} scale={[8.95, 0.43, 9.55]}>
            <mesh geometry={nodes.pCube11_lambert14_0.geometry} material={materials.lambert14} />
            <mesh geometry={nodes.pCube11_lambert17_0.geometry} material={materials.lambert17} />
            <mesh geometry={nodes.pCube11_lambert15_0.geometry} material={materials.lambert15} />
          </group>
          <group position={[-12, -1.18, 31]} scale={[0.99, 1.96, 0.99]}>
            <mesh geometry={nodes.pCylinder11_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder11_lambert8_0.geometry} material={materials.lambert8} />
            <mesh geometry={nodes.pCylinder11_lambert9_0.geometry} material={materials.lambert8} />
          </group>
          <group position={[-10, -1.19, 29]} scale={[0.99, 1.96, 0.99]}>
            <mesh geometry={nodes.pCylinder12_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder12_lambert8_0.geometry} material={materials.lambert8} />
            <mesh geometry={nodes.pCylinder12_lambert9_0.geometry} material={materials.lambert8} />
          </group>
          <group position={[7.44, -10.39, 42]} scale={[1.75, 5.59, 1.75]}>
            <mesh geometry={nodes.pCube16_lambert20_0.geometry} material={materials.lambert20} />
            <mesh geometry={nodes.pCube16_lambert19_0.geometry} material={materials.lambert19} />
          </group>
          <group position={[17.2, -10.39, 42]} scale={[1.75, 5.59, 1.75]}>
            <mesh geometry={nodes.pCube17_lambert20_0.geometry} material={materials.lambert20} />
            <mesh geometry={nodes.pCube17_lambert19_0.geometry} material={materials.lambert19} />
          </group>
          <group position={[17.2, -10.39, 27]} scale={[1.75, 5.59, 1.75]}>
            <mesh geometry={nodes.pCube18_lambert20_0.geometry} material={materials.lambert20} />
            <mesh geometry={nodes.pCube18_lambert19_0.geometry} material={materials.lambert19} />
          </group>
          <group position={[17.2, -10.39, 12]} scale={[1.75, 5.59, 1.75]}>
            <mesh geometry={nodes.pCube19_lambert20_0.geometry} material={materials.lambert20} />
            <mesh geometry={nodes.pCube19_lambert19_0.geometry} material={materials.lambert19} />
          </group>
          <group position={[-15.57, -10.39, 12]} scale={[1.75, 5.59, 1.75]}>
            <mesh geometry={nodes.pCube20_lambert20_0.geometry} material={materials.lambert20} />
            <mesh geometry={nodes.pCube20_lambert19_0.geometry} material={materials.lambert19} />
          </group>
          <group position={[-15.57, -10.39, 27]} scale={[1.75, 5.59, 1.75]}>
            <mesh geometry={nodes.pCube21_lambert20_0.geometry} material={materials.lambert20} />
            <mesh geometry={nodes.pCube21_lambert19_0.geometry} material={materials.lambert19} />
          </group>
          <group position={[0, -2.49, 37]} rotation={[Math.PI, -Math.PI / 6, -Math.PI / 2]} scale={0.52}>
            <mesh geometry={nodes.book_0005pCube12_book_0005phong1_0.geometry} material={materials.book_0005phong1} position={[-0.55, 1, -6]} rotation={[0, 0, -Math.PI / 2]} scale={[0.61, 0.03, 3.43]} />
            <mesh geometry={nodes.book_0005pSphere7_book_0005phongE2_0.geometry} material={materials.book_0005phongE2} position={[-0.44, -3.61, 4]} rotation={[0, -0.54, -Math.PI / 2]} scale={[0.15, 0.15, 0.38]} />
            <mesh geometry={nodes.book_0005pSphere6_book_0005phongE2_0.geometry} material={materials.book_0005phongE2} position={[-0.44, -3.61, 2.49]} rotation={[-Math.PI, -0.53, Math.PI / 2]} scale={[0.15, 0.15, 0.38]} />
            <mesh geometry={nodes.book_0005pCube14_lambert22_0.geometry} material={materials.lambert22} position={[1.26, 0, 0]} scale={[0.42, 0.74, 5.22]} />
            <mesh geometry={nodes.book_0005pSphere16_book_0005phongE3_0.geometry} material={materials.book_0005phongE3} position={[0, 0.6, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.7, 0.97, 1]} />
            <mesh geometry={nodes.book_0005pCylinder1_book_0005lambert3_0.geometry} material={materials.book_0005lambert3} position={[1.26, 2.3, 0.09]} rotation={[0, 0, -Math.PI / 2]} scale={[0.66, 0.06, 0.66]} />
            <mesh geometry={nodes.book_0005pCube5_book_0005phongE1_0.geometry} material={materials.book_0005phongE1} rotation={[-Math.PI, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.book_0005pSphere9_book_0005phongE2_0.geometry} material={materials.book_0005phongE2} position={[-0.44, -3.61, -2.27]} rotation={[0, -0.54, -Math.PI / 2]} scale={[0.15, 0.15, 0.38]} />
            <mesh geometry={nodes.book_0005pSphere8_book_0005phongE2_0.geometry} material={materials.book_0005phongE2} position={[-0.44, -3.61, -3.79]} rotation={[-Math.PI, -0.53, Math.PI / 2]} scale={[0.15, 0.15, 0.38]} />
            <mesh geometry={nodes.book_0005pCube10_book_0005lambert2_0.geometry} material={materials.book_0005lambert2} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 0.98]} />
            <mesh geometry={nodes.book_0005pSphere2_book_0005phongE2_0.geometry} material={materials.book_0005phongE2} position={[-0.44, -3.61, 0.87]} rotation={[0, -0.54, -Math.PI / 2]} scale={[0.15, 0.15, 0.38]} />
            <mesh geometry={nodes.book_0005pCube11_book_0005phong1_0.geometry} material={materials.book_0005phong1} position={[0.43, -2, -5.89]} rotation={[0, 0, -Math.PI / 2]} scale={[0.61, 0.03, 2.43]} />
            <mesh geometry={nodes.book_0005pSphere5_book_0005phongE2_0.geometry} material={materials.book_0005phongE2} position={[-0.44, -3.61, -0.65]} rotation={[-Math.PI, -0.53, Math.PI / 2]} scale={[0.15, 0.15, 0.38]} />
          </group>
          <group position={[-4.32, -2.45, 12]} rotation={[0, 0, -Math.PI / 2]} scale={0.39}>
            <mesh geometry={nodes.pSphere1_blinn10_0.geometry} material={materials.blinn7} position={[0, 0, 23]} rotation={[0, Math.PI / 4, 0]} />
            <mesh geometry={nodes.pSphere2_blinn10_0.geometry} material={materials.blinn7} position={[0, 5, 23]} rotation={[0, Math.PI / 4, 0]} />
          </group>
          <group position={[-10, -2.21, 25]} rotation={[-1.55, -0.02, -0.79]} scale={[0.99, 1.96, 0.99]}>
            <mesh geometry={nodes.pCylinder13_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder13_lambert8_0.geometry} material={materials.lambert8} />
            <mesh geometry={nodes.pCylinder13_lambert9_0.geometry} material={materials.lambert8} />
          </group>
          <group position={[4.74, -10.41, 19.82]} rotation={[-Math.PI / 2, 1.34, Math.PI / 2]} scale={0.62}>
            <group position={[-30.31, 17.27, 3]} rotation={[0, 0, -2.85]} scale={[0.49, 1.24, 0.49]}>
              <mesh geometry={nodes.sword2_0007pCylinder1_sword2_0007energytank_0002blinn2_0.geometry} material={materials.sword2_0007energytank_0002blinn2} />
              <mesh geometry={nodes.sword2_0007pCylinder1_sword2_0007energytank_0002blinn1_0.geometry} material={materials.sword2_0007energytank_0002blinn1} />
            </group>
            <group position={[14.97, 0, -13]}>
              <mesh geometry={nodes.sword2_0007pCylinder15_sword2_0007lambert5_0.geometry} material={materials.sword2_0007lambert5} />
              <mesh geometry={nodes.sword2_0007pCylinder15_sword2_0007blinn8_0.geometry} material={materials.sword2_0007blinn8} />
              <mesh geometry={nodes.sword2_0007pCylinder15_sword2_0007blinn9_0.geometry} material={materials.sword2_0007blinn8} />
            </group>
            <group position={[-24.84, 17.25, 3]} rotation={[0, 0, 2.83]} scale={[0.49, 1.24, 0.49]}>
              <mesh geometry={nodes.sword2_0007energytank_0002pCylinder1_sword2_0007energytank_0002blinn2_0.geometry} material={materials.sword2_0007energytank_0002blinn2} />
              <mesh geometry={nodes.sword2_0007energytank_0002pCylinder1_sword2_0007energytank_0002blinn1_0.geometry} material={materials.sword2_0007energytank_0002blinn1} />
            </group>
            <mesh geometry={nodes.sword2_0007pCylinder7_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-30.11, 16.91, 3.51]} rotation={[-0.09, 0.29, -1.27]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007pCylinder8_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-30.52, 17.63, 3.51]} rotation={[0.09, -0.29, 1.87]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007pCylinder5_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-30.34, 17.69, 3.51]} rotation={[-0.09, 0.29, -1.27]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007pCube1_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-30.31, 17.27, 3.49]} rotation={[Math.PI, 0, 2.85]} scale={[-0.35, 1.47, 0.07]} />
            <mesh geometry={nodes.sword2_0007pCube3_sword2_0007energytank_0002blinn5_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-29.84, 16.74, 3.41]} rotation={[-0.19, 0.58, -2.8]} scale={[0.13, 0.03, 0.01]} />
            <mesh geometry={nodes.sword2_0007pCylinder3_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-30.29, 16.86, 3.51]} rotation={[0.09, -0.29, 1.87]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007pCylinder2_sword2_0007energytank_0002phong1_0.geometry} material={materials.sword2_0007energytank_0002phong1} position={[-30.31, 17.27, 3.49]} rotation={[0, 0, -2.85]} scale={[0.04, 0.69, 0.04]} />
            <mesh geometry={nodes.sword2_0007pCylinder17_sword2_0007blinn4_0.geometry} material={materials.blinn6} position={[-31.24, 12.46, 3]} rotation={[Math.PI / 2, 1.57, 1.83]} scale={[0.43, 0.18, 0.38]} />
            <mesh geometry={nodes.sword2_0007pCylinder16_sword2_0007blinn4_0.geometry} material={materials.blinn6} position={[-31.48, 13.71, 3]} rotation={[Math.PI / 2, 1.57, Math.PI / 6]} scale={[0.43, 0.18, 0.38]} />
            <mesh geometry={nodes.sword2_0007pCube4_lambert27_0.geometry} material={materials.lambert27} position={[-29.74, 10.94, 3]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCylinder10_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-24.75, 17.22, 3.51]} rotation={[0.09, 0.29, -1.89]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCube2_sword2_0007energytank_0002blinn4_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-24.38, 17.77, 3.39]} rotation={[0.21, 0.57, 2.77]} scale={[0.15, 0.03, 0.01]} />
            <mesh geometry={nodes.sword2_0007pCube2_sword2_0007energytank_0002blinn4_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-30.22, 17.95, 3.39]} rotation={[-0.19, 0.58, -2.8]} scale={[0.15, 0.03, 0.01]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCylinder2_sword2_0007energytank_0002phong1_0.geometry} material={materials.sword2_0007energytank_0002phong1} position={[-24.84, 17.25, 3.49]} rotation={[0, 0, 2.83]} scale={[0.04, 0.69, 0.04]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCylinder3_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-25.05, 16.9, 3.51]} rotation={[-0.09, -0.29, 1.25]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007pCylinder9_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-30.4, 17.23, 3.51]} rotation={[0.09, -0.29, 1.87]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007pCylinder10_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-30.22, 17.29, 3.51]} rotation={[-0.09, 0.29, -1.27]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007pSphere1_sword2_0007energytank_0002blinn3_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-30.11, 16.59, 3.54]} rotation={[0, 0, -2.85]} scale={0.01} />
            <mesh geometry={nodes.sword2_0007pSphere2_sword2_0007energytank_0002blinn3_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-30.51, 17.93, 3.54]} rotation={[0, 0, -2.85]} scale={0.01} />
            <mesh geometry={nodes.sword2_0007energytank_0002pSphere2_sword2_0007energytank_0002blinn3_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-24.63, 17.91, 3.54]} rotation={[0, 0, 2.83]} scale={0.01} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCylinder9_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-24.94, 17.27, 3.51]} rotation={[-0.09, -0.29, 1.25]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCylinder8_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-24.81, 17.67, 3.51]} rotation={[-0.09, -0.29, 1.25]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCylinder5_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-24.63, 17.62, 3.51]} rotation={[0.09, 0.29, -1.89]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pSphere1_sword2_0007energytank_0002blinn3_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-25.05, 16.58, 3.54]} rotation={[0, 0, 2.83]} scale={0.01} />
            <mesh geometry={nodes.sword2_0007pCylinder18_lambert28_0.geometry} material={materials.lambert28} position={[-27.57, 11.36, 3]} rotation={[0, 1.31, 0]} scale={[1.05, 8.35, 1.05]} />
            <mesh geometry={nodes.sword2_0007pCylinder19_lambert29_0.geometry} material={materials.lambert29} position={[-27.57, 21.12, 3]} rotation={[Math.PI / 2, 0, 0]} scale={[1.06, 0.44, 0.92]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCube3_sword2_0007energytank_0002blinn5_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-24.75, 16.56, 3.41]} rotation={[0.21, 0.57, 2.77]} scale={[0.13, 0.03, 0.01]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCylinder7_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-24.87, 16.85, 3.51]} rotation={[0.09, 0.29, -1.89]} scale={[0.04, 0.04, 0.01]} />
            <mesh geometry={nodes.sword2_0007energytank_0002pCube1_sword2_0007energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-24.84, 17.25, 3.49]} rotation={[Math.PI, 0, -2.83]} scale={[-0.35, 1.47, 0.07]} />
          </group>
          <group position={[9.88, -3.64, 27.31]} rotation={[-Math.PI, -Math.PI / 3, -Math.PI]} scale={0.58}>
            <group position={[1.2, -11.44, 5.49]} rotation={[0, Math.PI / 2, 0]} scale={[1.33, 1.24, 2.54]}>
              <mesh geometry={nodes.clank_0015pSphere3_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} />
              <mesh geometry={nodes.clank_0015pSphere3_clank_0015phong4_0.geometry} material={materials.clank_0015blinn2} />
            </group>
            <group position={[1.2, -11.44, 2.11]} rotation={[0, Math.PI / 2, 0]} scale={[1.33, 1.24, 2.54]}>
              <mesh geometry={nodes.clank_0015pSphere2_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} />
              <mesh geometry={nodes.clank_0015pSphere2_clank_0015phong3_0.geometry} material={materials.clank_0015blinn2} />
              <mesh geometry={nodes.clank_0015pSphere2_clank_0015phong2_0.geometry} material={materials.clank_0015blinn2} />
            </group>
            <group position={[-0.03, 4.47, 3.61]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[3.23, 2.62, 2.66]}>
              <mesh geometry={nodes.clank_0015pSphere8_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} />
              <mesh geometry={nodes.clank_0015pSphere8_clank_0015blinn6_0.geometry} material={materials.clank_0015blinn2} />
            </group>
            <group position={[1.71, -2.31, 3.76]} rotation={[0, 0, 0.08]} scale={[1, 3.26, 3.08]}>
              <mesh geometry={nodes.clank_0015pCube41_clank_0015blinn3_0.geometry} material={materials.clank_0015blinn2} />
              <mesh geometry={nodes.clank_0015pCube41_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} />
            </group>
            <group position={[0, 9.46, 3.74]} scale={0.52}>
              <mesh geometry={nodes.clank_0015pSphere6_clank_0015phong1_0.geometry} material={materials.lambert17} />
              <mesh geometry={nodes.clank_0015pSphere6_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} />
            </group>
            <group position={[0, -1.78, 3.77]} rotation={[0, Math.PI / 2, 0]} scale={5.13}>
              <mesh geometry={nodes.clank_0015pCube1_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} />
              <mesh geometry={nodes.clank_0015pCube1_clank_0015blinn4_0.geometry} material={materials.clank_0015blinn2} />
            </group>
            <mesh geometry={nodes.clank_0015pCube45_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[5.94, -2.47, 0.94]} rotation={[-1.32, 1.02, 1.13]} scale={[0.59, 0.83, 1.2]} />
            <mesh geometry={nodes.clank_0015pCube8_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[6.74, -3.91, 1.29]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[0.42, 1.99, 0.46]} />
            <mesh geometry={nodes.clank_0015pCube4_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[6.55, -3.8, 1.23]} rotation={[Math.PI / 2, -Math.PI / 6, 1.83]} scale={[0.64, 0.91, 1]} />
            <mesh geometry={nodes.clank_0015pCube46_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[6.79, -1.95, 1.15]} rotation={[-1.03, 0.92, 0.89]} scale={[0.45, 0.62, 0.61]} />
            <mesh geometry={nodes.clank_0015pCube7_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[6.79, -5.38, 1.5]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[0.53, 0.95, 0.96]} />
            <mesh geometry={nodes.clank_0015pCube9_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[6.11, -5, 1.29]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[0.42, 1.99, 0.46]} />
            <mesh geometry={nodes.clank_0015pCube6_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[5.92, -4.89, 1.23]} rotation={[Math.PI / 2, -Math.PI / 6, 1.83]} scale={[0.64, 0.91, 1]} />
            <mesh geometry={nodes.clank_0015pCube5_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[7.42, -4.28, 1.5]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[0.53, 0.95, 0.96]} />
            <mesh geometry={nodes.clank_0015pCube2_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[4.68, -3.45, 0.78]} rotation={[-Math.PI / 2, Math.PI / 6, 1.31]} scale={[1.04, 2.57, 2.66]} />
            <mesh geometry={nodes.clank_0015pCube25_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[2.17, -2, 0.29]} rotation={[-Math.PI / 2, -0.26, Math.PI / 2]} scale={[0.58, 0.58, 0.63]} />
            <mesh geometry={nodes.clank_0015pCube28_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[-0.01, -0.74, 0.51]} rotation={[Math.PI / 2, -Math.PI / 3, -Math.PI / 2]} scale={[1.1, 1.1, 1.19]} />
            <mesh geometry={nodes.clank_0015pCylinder15_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[2.41, -2.14, 0.7]} rotation={[0, 0, Math.PI / 3]} scale={[0.35, 2.93, 0.35]} />
            <mesh geometry={nodes.clank_0015pCylinder14_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0.03, -0.77, 3.75]} rotation={[Math.PI / 2, Math.PI / 3, 0]} scale={[0.31, 3.18, 0.31]} />
            <mesh geometry={nodes.clank_0015pCylinder1_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -0.75, 0.72]} rotation={[-Math.PI / 2, -Math.PI / 3, 0]} scale={[1.1, 0.49, 1.1]} />
            <mesh geometry={nodes.clank_0015pCylinder6_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[2.18, -2.01, 0.68]} rotation={[Math.PI / 2, Math.PI / 3, 0]} scale={[0.59, 0.47, 0.59]} />
            <mesh geometry={nodes.clank_0015pCube54_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0.6, -1.71, 2]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.38, 0.38, 0.41]} />
            <mesh geometry={nodes.clank_0015pCube53_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[-0.66, -1.71, 2]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.38, 0.38, 0.41]} />
            <mesh geometry={nodes.clank_0015pCube52_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0.6, -1.71, 5.55]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.38, 0.38, 0.41]} />
            <mesh geometry={nodes.clank_0015pCube51_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[-0.66, -1.71, 5.55]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.38, 0.38, 0.41]} />
            <mesh geometry={nodes.clank_0015pCube50_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[-2.29, -1.04, 3.74]} rotation={[0, 0, -2.94]} scale={[0.06, 0.32, 1.29]} />
            <mesh geometry={nodes.clank_0015pCube49_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[-2.31, -1.5, 3.74]} rotation={[0, 0, -2.94]} scale={[0.06, 0.32, 1.29]} />
            <mesh geometry={nodes.clank_0015pCube48_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[-2.33, -1.96, 3.74]} rotation={[0, 0, -2.94]} scale={[0.06, 0.32, 1.29]} />
            <mesh geometry={nodes.clank_0015pCube47_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[-1.69, -1.57, 3.76]} rotation={[0, 0, 3.05]} scale={[0.89, 2.06, 1.95]} />
            <mesh geometry={nodes.clank_0015pCylinder9_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, 1.09, 3.74]} scale={[0.44, 0.78, 0.44]} />
            <mesh geometry={nodes.clank_0015pCylinder8_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -7.49, 5.46]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 0.58, 0.71]} />
            <mesh geometry={nodes.clank_0015pCylinder12_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -9.68, 2.19]} rotation={[Math.PI / 2, 0, 0]} scale={[0.58, 0.87, 0.58]} />
            <mesh geometry={nodes.clank_0015pCylinder4_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -5.35, 3.74]} rotation={[Math.PI / 2, 0, 0]} scale={[0.25, 2.25, 0.25]} />
            <mesh geometry={nodes.clank_0015pCylinder3_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, 0.75, 3.74]} scale={[0.77, 0.35, 0.77]} />
            <mesh geometry={nodes.clank_0015pCylinder10_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -5.62, 5.49]} scale={[0.42, 0.65, 0.42]} />
            <mesh geometry={nodes.clank_0015pCylinder11_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -9.68, 5.4]} rotation={[Math.PI / 2, 0, 0]} scale={[0.58, 0.87, 0.58]} />
            <mesh geometry={nodes.clank_0015pCylinder13_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -5.62, 2.04]} scale={[0.42, 0.65, 0.42]} />
            <mesh geometry={nodes.clank_0015pCylinder18_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -8.46, 2.05]} rotation={[-Math.PI, 0, 0]} scale={[0.35, 2.44, 0.35]} />
            <mesh geometry={nodes.clank_0015pSphere10_clank_0015phongE1_0.geometry} material={materials.clank_0015phongE1} position={[2.26, 5.2, 2.81]} rotation={[-2.25, 1.24, 2.24]} scale={[0.79, 0.79, 0.43]} />
            <mesh geometry={nodes.clank_0015pSphere9_clank_0015phongE1_0.geometry} material={materials.clank_0015phongE1} position={[2.2, 5.2, 4.84]} rotation={[-0.7, 1.18, 0.74]} scale={[0.79, 0.79, 0.43]} />
            <mesh geometry={nodes.clank_0015pCube3_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[5.43, -0.65, 6.75]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[1.04, 2.57, 2.66]} />
            <mesh geometry={nodes.clank_0015pCylinder25_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[6.32, 1.37, 6.39]} rotation={[-1.72, 0.5, -1.27]} scale={[0.07, 0.27, 0.1]} />
            <mesh geometry={nodes.clank_0015pCube10_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[8.21, -1.27, 6.01]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[0.53, 0.95, 0.96]} />
            <mesh geometry={nodes.clank_0015pCube15_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[7.21, -0.02, 6.28]} rotation={[Math.PI / 2, 0, 1.31]} scale={[0.64, 0.91, 1]} />
            <mesh geometry={nodes.clank_0015pCube14_clank_0015blinn5_0.geometry} material={materials.clank_0015blinn2} position={[7.43, -1.28, 6.22]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[0.42, 1.99, 0.46]} />
            <mesh geometry={nodes.clank_0015pCube13_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[7.43, -0.02, 6.22]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[0.42, 1.99, 0.46]} />
            <mesh geometry={nodes.clank_0015pCube11_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[7.21, -1.28, 6.28]} rotation={[Math.PI / 2, 0, 1.31]} scale={[0.64, 0.91, 1]} />
            <mesh geometry={nodes.clank_0015pCube12_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[8.21, 0, 6.01]} rotation={[-Math.PI / 2, 0, 1.83]} scale={[0.53, 0.95, 0.96]} />
            <mesh geometry={nodes.clank_0015pCube17_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[6.48, 1.7, 6.3]} rotation={[-1.92, 0.44, -1.18]} scale={[0.45, 0.62, 0.61]} />
            <mesh geometry={nodes.clank_0015pCube24_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[5.09, -0.65, 7.25]} rotation={[0, -1.31, 0]} scale={[0.74, 0.74, 0.79]} />
            <mesh geometry={nodes.clank_0015pCube16_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[6, 0.82, 6.51]} rotation={[-1.72, 0.5, -1.27]} scale={[0.59, 0.83, 1.2]} />
            <mesh geometry={nodes.clank_0015pCube26_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[2.53, -0.65, 7.23]} rotation={[-Math.PI / 2, Math.PI / 4, -Math.PI / 2]} scale={[0.58, 0.58, 0.63]} />
            <mesh geometry={nodes.clank_0015pCylinder16_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[2.81, -0.65, 6.83]} rotation={[0, 0, Math.PI / 2]} scale={[0.35, 2.93, 0.35]} />
            <mesh geometry={nodes.clank_0015pCylinder5_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[2.54, -0.65, 6.86]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.59, 0.47, 0.59]} />
            <mesh geometry={nodes.clank_0015pCylinder2_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0.02, -0.65, 6.79]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1.1, 0.49, 1.1]} />
            <mesh geometry={nodes.clank_0015pCube27_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0.01, -0.65, 7]} rotation={[Math.PI / 2, Math.PI / 6, Math.PI / 2]} scale={[1.1, 1.1, 1.19]} />
            <mesh geometry={nodes.clank_0015pCylinder21_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[6.47, -2.13, 1.05]} rotation={[-1.32, 1.02, 1.13]} scale={[0.07, 0.27, 0.1]} />
            <mesh geometry={nodes.clank_0015pCube22_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[4.38, -3.28, 0.3]} rotation={[-2.06, -0.99, 1.15]} scale={[0.74, 0.74, 0.79]} />
            <mesh geometry={nodes.clank_0015pCube29_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -9.67, 1.48]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.74, 0.74, 0.79]} />
            <mesh geometry={nodes.clank_0015pCube33_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0.61, 3.86, 1.23]} rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 2]} scale={[0.65, 0.65, 0.7]} />
            <mesh geometry={nodes.clank_0015pCube37_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -7.49, 5.86]} rotation={[Math.PI / 2, -Math.PI / 3, Math.PI / 2]} scale={[0.76, 0.76, 0.82]} />
            <mesh geometry={nodes.clank_0015pCube38_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -7.49, 5.04]} rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI / 2]} scale={[0.76, 0.76, 0.82]} />
            <mesh geometry={nodes.clank_0015pCube34_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0.61, 3.86, 6.25]} rotation={[Math.PI / 2, Math.PI / 4, Math.PI / 2]} scale={[0.65, 0.65, 0.7]} />
            <mesh geometry={nodes.clank_0015pCube39_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -5.34, 1.54]} rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 2]} scale={[0.25, 0.25, 0.27]} />
            <mesh geometry={nodes.clank_0015pCube40_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -5.34, 5.96]} rotation={[Math.PI / 2, Math.PI / 4, Math.PI / 2]} scale={[0.25, 0.25, 0.27]} />
            <mesh geometry={nodes.clank_0015pCube42_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[2.35, -1.55, 3.74]} rotation={[0, 0, 0.47]} scale={[0.07, 0.48, 2.04]} />
            <mesh geometry={nodes.clank_0015pCube44_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[2.46, -3, 3.74]} rotation={[0, 0, 0.47]} scale={[0.07, 0.48, 2.04]} />
            <mesh geometry={nodes.clank_0015pCube43_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[2.41, -2.29, 3.74]} rotation={[0, 0, 0.47]} scale={[0.07, 0.48, 2.04]} />
            <mesh geometry={nodes.clank_0015pCylinder17_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -8.46, 5.48]} rotation={[-Math.PI, 0, 0]} scale={[0.35, 2.44, 0.35]} />
            <mesh geometry={nodes.clank_0015pSphere5_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -0.76, 5.37]} scale={0.52} />
            <mesh geometry={nodes.clank_0015pCylinder19_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, 7.09, 3.75]} scale={0.46} />
            <mesh geometry={nodes.clank_0015pCylinder24_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0.6, 3.85, 3.74]} rotation={[Math.PI / 2, 0, 0]} scale={[0.82, 2.65, 0.82]} />
            <mesh geometry={nodes.clank_0015pSphere4_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -0.76, 2.16]} scale={0.52} />
            <mesh geometry={nodes.clank_0015pCube36_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -7.49, 2.46]} rotation={[Math.PI / 2, -Math.PI / 3, Math.PI / 2]} scale={[0.76, 0.76, 0.82]} />
            <mesh geometry={nodes.clank_0015pCube30_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -9.67, 2.9]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.74, 0.74, 0.79]} />
            <mesh geometry={nodes.clank_0015pCube31_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -9.67, 6.11]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.74, 0.74, 0.79]} />
            <mesh geometry={nodes.clank_0015pCube32_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -9.67, 4.68]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.74, 0.74, 0.79]} />
            <mesh geometry={nodes.clank_0015pCube35_clank_0015blinn2_0.geometry} material={materials.clank_0015blinn2} position={[0, -7.49, 1.64]} rotation={[-Math.PI / 2, -Math.PI / 3, Math.PI / 2]} scale={[0.76, 0.76, 0.82]} />
            <mesh geometry={nodes.clank_0015pCylinder7_clank_0015blinn1_0.geometry} material={materials.clank_0015blinn1} position={[0, -7.49, 2.04]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 0.58, 0.71]} />
          </group>
          <group position={[16, -9.03, 21]} rotation={[-Math.PI / 2, 1.31, 0]} scale={0.64}>
            <group scale={[2, 5.05, 2]}>
              <mesh geometry={nodes.energytank_0002pCylinder1_energytank_0002blinn2_0.geometry} material={materials.sword2_0007energytank_0002blinn2} />
              <mesh geometry={nodes.energytank_0002pCylinder1_energytank_0002blinn1_0.geometry} material={materials.sword2_0007energytank_0002blinn1} />
            </group>
            <mesh geometry={nodes.energytank_0002pCylinder3_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0.4, 1.63, 2.08]} rotation={[0, 0.3, -Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.energytank_0002pCylinder2_energytank_0002phong1_0.geometry} material={materials.sword2_0007energytank_0002phong1} position={[0, 0, 1.99]} scale={[0.17, 2.82, 0.17]} />
            <mesh geometry={nodes.energytank_0002pCube1_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0, 0, 2.02]} rotation={[-Math.PI, 0, 0]} scale={[-1.45, 5.99, 0.29]} />
            <mesh geometry={nodes.energytank_0002pCube3_energytank_0002blinn5_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-1.22, 2.58, 1.67]} rotation={[0, -0.6, 0]} scale={[0.54, 0.14, 0.05]} />
            <mesh geometry={nodes.energytank_0002pCube2_energytank_0002blinn4_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-1.14, -2.58, 1.6]} rotation={[0, -0.61, 0]} scale={[0.63, 0.14, 0.05]} />
            <mesh geometry={nodes.energytank_0002pCylinder10_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-0.36, 0.01, 2.08]} rotation={[0, -0.3, Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.energytank_0002pCylinder9_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0.4, 0.03, 2.08]} rotation={[0, 0.3, -Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.energytank_0002pCylinder8_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0.4, -1.68, 2.08]} rotation={[0, 0.3, -Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.energytank_0002pCylinder7_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-0.36, 1.61, 2.08]} rotation={[0, -0.3, Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.energytank_0002pSphere2_energytank_0002blinn3_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[0, -2.82, 2.18]} scale={[0.06, 0.06, 0.02]} />
            <mesh geometry={nodes.energytank_0002pSphere1_energytank_0002blinn3_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[0, 2.86, 2.18]} scale={[0.06, 0.06, 0.02]} />
            <mesh geometry={nodes.energytank_0002pCylinder5_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-0.36, -1.7, 2.08]} rotation={[0, -0.3, Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
          </group>
          <group position={[13.33, -9.03, 22.24]} rotation={[-Math.PI / 2, 0.26, 0]} scale={0.64}>
            <group scale={[2, 5.05, 2]}>
              <mesh geometry={nodes.pCylinder1_energytank_0002blinn2_0.geometry} material={materials.sword2_0007energytank_0002blinn2} />
              <mesh geometry={nodes.pCylinder1_energytank_0002blinn1_0.geometry} material={materials.sword2_0007energytank_0002blinn1} />
            </group>
            <mesh geometry={nodes.pCylinder3_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0.4, 1.63, 2.08]} rotation={[0, 0.3, -Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pCylinder2_energytank_0002phong1_0.geometry} material={materials.sword2_0007energytank_0002phong1} position={[0, 0, 1.99]} scale={[0.17, 2.82, 0.17]} />
            <mesh geometry={nodes.pCube1_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0, 0, 2.02]} rotation={[Math.PI, 0, 0]} scale={[-1.45, 5.99, 0.29]} />
            <mesh geometry={nodes.pPlane1_energytank_0002lambert2_0.geometry} material={materials.blinn6} position={[1.55, 0, 1.14]} rotation={[0, -0.61, -Math.PI / 2]} />
            <mesh geometry={nodes.pCube3_energytank_0002blinn5_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-1.22, 2.58, 1.67]} rotation={[0, -0.6, 0]} scale={[0.54, 0.14, 0.05]} />
            <mesh geometry={nodes.pCube2_energytank_0002blinn4_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-1.14, -2.58, 1.6]} rotation={[0, -0.61, 0]} scale={[0.63, 0.14, 0.05]} />
            <mesh geometry={nodes.pCylinder10_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-0.36, 0.01, 2.08]} rotation={[0, -0.3, Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pCylinder9_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0.4, 0.03, 2.08]} rotation={[0, 0.3, -Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pCylinder8_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0.4, -1.68, 2.08]} rotation={[0, 0.3, -Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pCylinder7_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-0.36, 1.61, 2.08]} rotation={[0, -0.3, Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pSphere2_energytank_0002blinn3_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[0, -2.82, 2.18]} scale={[0.06, 0.06, 0.02]} />
            <mesh geometry={nodes.pSphere1_energytank_0002blinn3_0.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[0, 2.86, 2.18]} scale={[0.06, 0.06, 0.02]} />
            <mesh geometry={nodes.pCylinder5_energytank_0002phongE1_0.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-0.36, -1.7, 2.08]} rotation={[0, -0.3, Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
          </group>
          <group position={[14.83, -6.8, 21.24]} rotation={[-Math.PI / 2, -Math.PI / 6, 0]} scale={0.64}>
            <group scale={[2, 5.05, 2]}>
              <mesh geometry={nodes.pCylinder1_energytank_0002blinn2_0_1.geometry} material={materials.sword2_0007energytank_0002blinn2} />
              <mesh geometry={nodes.pCylinder1_energytank_0002blinn1_0_1.geometry} material={materials.sword2_0007energytank_0002blinn1} />
            </group>
            <mesh geometry={nodes.pCylinder3_energytank_0002phongE1_0_1.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0.4, 1.63, 2.08]} rotation={[0, 0.3, -Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pCylinder2_energytank_0002phong1_0_1.geometry} material={materials.sword2_0007energytank_0002phong1} position={[0, 0, 1.99]} scale={[0.17, 2.82, 0.17]} />
            <mesh geometry={nodes.pCube1_energytank_0002phongE1_0_1.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0, 0, 2.02]} rotation={[-Math.PI, 0, 0]} scale={[-1.45, 5.99, 0.29]} />
            <mesh geometry={nodes.pCube3_energytank_0002blinn5_0_1.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-1.22, 2.58, 1.67]} rotation={[0, -0.6, 0]} scale={[0.54, 0.14, 0.05]} />
            <mesh geometry={nodes.pCube2_energytank_0002blinn4_0_1.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[-1.14, -2.58, 1.6]} rotation={[0, -0.61, 0]} scale={[0.63, 0.14, 0.05]} />
            <mesh geometry={nodes.pCylinder10_energytank_0002phongE1_0_1.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-0.36, 0.01, 2.08]} rotation={[0, -0.3, Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pCylinder9_energytank_0002phongE1_0_1.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0.4, 0.03, 2.08]} rotation={[0, 0.3, -Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pCylinder8_energytank_0002phongE1_0_1.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[0.4, -1.68, 2.08]} rotation={[0, 0.3, -Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pCylinder7_energytank_0002phongE1_0_1.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-0.36, 1.61, 2.08]} rotation={[0, -0.3, Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
            <mesh geometry={nodes.pSphere2_energytank_0002blinn3_0_1.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[0, -2.82, 2.18]} scale={[0.06, 0.06, 0.02]} />
            <mesh geometry={nodes.pSphere1_energytank_0002blinn3_0_1.geometry} material={materials.sword2_0007energytank_0002blinn5} position={[0, 2.86, 2.18]} scale={[0.06, 0.06, 0.02]} />
            <mesh geometry={nodes.pCylinder5_energytank_0002phongE1_0_1.geometry} material={materials.sword2_0007energytank_0002phongE1} position={[-0.36, -1.7, 2.08]} rotation={[0, -0.3, Math.PI / 2]} scale={[0.17, 0.17, 0.03]} />
          </group>
          <group position={[30.92, -22.88, 0]} rotation={[0, 0, 1.25]}>
            <group position={[18.35, 26.15, 9.55]} rotation={[-1.54, -0.3, -1.56]} scale={0.22}>
              <group position={[19, 5.96, 10.35]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.69, 2.46, 1.4]}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder3_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder3_NMSMultyTool_0010phong9_0.geometry} material={materials.NMSMultyTool_0010phong9} />
              </group>
              <group position={[20.28, 3.85, 3.37]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.86, 1.52, 0.92]}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong8_0.geometry} material={materials.NMSMultyTool_0010phong8} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong7_0.geometry} material={materials.NMSMultyTool_0010phong7} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder7_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} />
              </group>
              <group position={[18.87, 3.79, -0.26]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[0.86, 1.52, 0.92]}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong8_0.geometry} material={materials.NMSMultyTool_0010phong8} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong7_0.geometry} material={materials.NMSMultyTool_0010phong7} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder8_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} />
              </group>
              <group position={[19, 2.5, 10.45]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.05, 1.53, 0.95]}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder4_NMSMultyTool_0010phong10_0.geometry} material={materials.NMSMultyTool_0010phong9} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder4_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} />
              </group>
              <group position={[19, 5.17, 6.54]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[1.92, 2.79, 1.68]}>
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong8_0.geometry} material={materials.NMSMultyTool_0010phong8} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong7_0.geometry} material={materials.NMSMultyTool_0010phong7} />
                <mesh geometry={nodes.NMSMultyTool_0010pCylinder2_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} />
              </group>
              <group position={[19, 4.26, 10.98]} rotation={[0, -Math.PI / 2, 0]} scale={[1.96, 6.41, 3.93]}>
                <mesh geometry={nodes.NMSMultyTool_0010pCube2_NMSMultyTool_0010phong4_0.geometry} material={materials.NMSMultyTool_0010phong2} />
                <mesh geometry={nodes.NMSMultyTool_0010pCube2_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} />
              </group>
              <group position={[19, -1.82, 6.62]} scale={[2.45, 4.72, 2.45]}>
                <mesh geometry={nodes.NMSMultyTool_0010pCube1_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} />
                <mesh geometry={nodes.NMSMultyTool_0010pCube1_NMSMultyTool_0010phong3_0.geometry} material={materials.NMSMultyTool_0010phong2} />
              </group>
              <group position={[19, 6.5, 4.33]} scale={[3, 3, 7.07]}>
                <mesh geometry={nodes.NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} />
                <mesh geometry={nodes.NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong5_0.geometry} material={materials.NMSMultyTool_0010phong5} />
                <mesh geometry={nodes.NMSMultyTool_0010pSphere1_NMSMultyTool_0010phong6_0.geometry} material={materials.NMSMultyTool_0010phong5} />
              </group>
              <mesh geometry={nodes.NMSMultyTool_0010pSphere2_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} position={[19, 2.27, 4.33]} rotation={[0, 0, -Math.PI]} scale={[3, 3, 7.07]} />
              <mesh geometry={nodes.NMSMultyTool_0010pCylinder5_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} position={[22.41, 3.77, -0.73]} rotation={[-1.59, 0, 0]} scale={[0.46, 4.83, 0.46]} />
              <mesh geometry={nodes.NMSMultyTool_0010pCube3_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} position={[19, -1.15, 4.39]} rotation={[0, -Math.PI / 2, 0]} scale={[12.11, 4.62, 3.47]} />
              <mesh geometry={nodes.NMSMultyTool_0010pSphere3_NMSMultyTool_0010phong1_0.geometry} material={materials.NMSMultyTool_0010phong1} position={[19, 4.55, 4.57]} rotation={[0, -Math.PI / 2, 0]} scale={[6.61, 3.91, 2.79]} />
              <mesh geometry={nodes.NMSMultyTool_0010pCylinder1_NMSMultyTool_0010phong2_0.geometry} material={materials.NMSMultyTool_0010phong2} position={[19, -1.03, 8.5]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[1.06, 2.41, 1.26]} />
            </group>
          </group>
          <mesh geometry={nodes.pCube2_lambert4_0.geometry} material={materials.lambert4} position={[0.86, -11, 27]} rotation={[-Math.PI, 0, -Math.PI]} scale={[32.98, 1.43, 30.07]} />
          <mesh geometry={nodes.pCube4_lambert11_0.geometry} material={materials.lambert11} position={[6.95, -3.92, 13]} scale={[0.93, 13.86, 1.67]} />
          <mesh geometry={nodes.pCube5_lambert11_0.geometry} material={materials.lambert11} position={[14.95, -3.92, 13]} scale={[0.93, 13.86, 1.67]} />
          <mesh geometry={nodes.pCube6_lambert11_0.geometry} material={materials.lambert11} position={[14.99, 3.29, 13]} rotation={[0, 0, Math.PI / 2]} scale={[0.93, 1.72, 2.19]} />
          <mesh geometry={nodes.pCube7_lambert11_0.geometry} material={materials.lambert11} position={[6.99, 3.29, 13]} rotation={[0, 0, Math.PI / 2]} scale={[0.93, 1.72, 2.19]} />
          <mesh geometry={nodes.pCube8_lambert11_0.geometry} material={materials.lambert11} position={[11, -10.15, 13.37]} rotation={[0, 0, Math.PI / 2]} scale={[0.93, 8.01, 1.67]} />
          <mesh geometry={nodes.pCube9_lambert12_0.geometry} material={materials.lambert13} position={[11, -3.36, 13]} scale={[7.53, 13.39, 0.47]} />
          <mesh geometry={nodes.pCylinder2_lambert10_0.geometry} material={materials.lambert10} position={[4.38, -9.31, 18.38]} scale={[1.05, 1.23, 1.05]} />
          <mesh geometry={nodes.pCylinder3_lambert10_0.geometry} material={materials.lambert10} position={[-4.94, -9.31, 18.38]} scale={[1.05, 1.23, 1.05]} />
          <mesh geometry={nodes.pCylinder4_lambert10_0.geometry} material={materials.lambert10} position={[-4.94, -9.31, 14.26]} scale={[1.05, 1.23, 1.05]} />
          <mesh geometry={nodes.pCylinder5_lambert10_0.geometry} material={materials.lambert10} position={[4.38, -9.31, 14.26]} scale={[1.05, 1.23, 1.05]} />
          <mesh geometry={nodes.pPlane2_phong1_0.geometry} material={materials.phong1} position={[-9.85, 3.93, 32.79]} rotation={[Math.PI / 2, 0, 0]} scale={[4.84, 2, 1.82]} />
          <mesh geometry={nodes.pCylinder8_lambert18_0.geometry} material={materials.lambert19} position={[-14.24, 0.96, 28.41]} scale={[0.36, 5.08, 0.36]} />
          <mesh geometry={nodes.pCylinder9_lambert18_0.geometry} material={materials.lambert19} position={[-14.24, 0.96, 21.59]} scale={[0.36, 5.08, 0.36]} />
          <mesh geometry={nodes.pCylinder10_lambert18_0.geometry} material={materials.lambert19} position={[-14.29, 1.97, 25.56]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.29, 4.5, 0.29]} />
          <mesh geometry={nodes.pCube13_lambert5_0.geometry} material={materials.lambert6} position={[12.2, -12.58, 43.97]} scale={[9.84, 1.22, 2.84]} />
          <mesh geometry={nodes.pCube14_lambert5_0.geometry} material={materials.lambert6} position={[8.2, -11.04, 43.28]} rotation={[Math.PI / 4, Math.PI / 2, 0]} scale={[4.41, 1.22, 1.83]} />
          <mesh geometry={nodes.pCube15_lambert5_0.geometry} material={materials.lambert6} position={[16.2, -11.04, 43.28]} rotation={[Math.PI / 4, Math.PI / 2, 0]} scale={[4.41, 1.22, 1.83]} />
          <mesh geometry={nodes.pPlane3_lambert21_0.geometry} material={materials.lambert21} position={[0, 1.52, 24]} rotation={[Math.PI / 2, 0, 0]} scale={[9, 9, 9.2]} />
          <mesh geometry={nodes.pTorus1_blinn8_0.geometry} material={materials.blinn7} position={[-11.53, 5.33, 33]} rotation={[Math.PI / 2, 0, -Math.PI / 3]} scale={[0.4, 0.4, 0.49]} />
          <mesh geometry={nodes.pTorus2_blinn8_0.geometry} material={materials.blinn7} position={[-11.53, 6, 33]} rotation={[Math.PI / 2, 0, 0]} scale={[0.4, 0.4, 0.49]} />
          <mesh geometry={nodes.pTorus3_blinn8_0.geometry} material={materials.blinn7} position={[-8.18, 6, 33]} rotation={[Math.PI / 2, 0, 2.09]} scale={[0.4, 0.4, 0.49]} />
          <mesh geometry={nodes.pTorus4_blinn8_0.geometry} material={materials.blinn7} position={[-8.18, 5.33, 33]} rotation={[Math.PI / 2, 0, Math.PI / 3]} scale={[0.4, 0.4, 0.49]} />
          <mesh geometry={nodes.pCylinder14_blinn11_0.geometry} material={materials.lambert22} position={[8.87, 0.45, 13.36]} rotation={[Math.PI / 2, -0.2, 0]} scale={[0.64, 0.13, 0.64]} />
          <mesh geometry={nodes.pCylinder15_blinn11_0.geometry} material={materials.lambert22} position={[10.76, -0.07, 13.36]} rotation={[Math.PI / 2, 0.24, 0]} scale={[0.64, 0.13, 0.64]} />
          <mesh geometry={nodes.pCylinder16_blinn11_0.geometry} material={materials.lambert22} position={[13.03, 0.45, 13.36]} rotation={[Math.PI / 2, 0, 0]} scale={[0.64, 0.13, 0.64]} />
          <mesh geometry={nodes.pCylinder17_blinn11_0.geometry} material={materials.lambert22} position={[13.03, -2.97, 13.36]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.64, 0.13, 0.64]} />
          <mesh geometry={nodes.pCylinder18_blinn11_0.geometry} material={materials.lambert22} position={[10.76, -2.97, 13.36]} rotation={[Math.PI / 2, 0.24, -Math.PI]} scale={[0.64, 0.13, 0.64]} />
          <mesh geometry={nodes.pCylinder19_blinn11_0.geometry} material={materials.lambert22} position={[8.87, -2.97, 13.36]} rotation={[Math.PI / 2, -0.2, -Math.PI]} scale={[0.64, 0.13, 0.64]} />
          <mesh geometry={nodes.pCylinder20_blinn11_0.geometry} material={materials.lambert22} position={[13.03, -6.49, 13.36]} rotation={[Math.PI / 2, 0, -0.03]} scale={[0.64, 0.13, 0.64]} />
          <mesh geometry={nodes.pCylinder21_blinn11_0.geometry} material={materials.lambert22} position={[10.76, -6.49, 13.36]} rotation={[Math.PI / 2, 0.24, -Math.PI]} scale={[0.64, 0.13, 0.64]} />
          <mesh geometry={nodes.pCylinder22_blinn11_0.geometry} material={materials.lambert22} position={[8.87, -6.49, 13.36]} rotation={[Math.PI / 2, -0.2, -0.03]} scale={[0.64, 0.13, 0.64]} />
          <mesh geometry={nodes.GhjostCereals_0003pCube1_GhjostCereals_0003lambert2_0.geometry} material={materials.GhjostCereals_0003lambert2} position={[-9.97, -0.4, 37.05]} rotation={[0, Math.PI / 4, 0]} scale={[4.08, 5.52, 1.22]} />
          <mesh geometry={nodes.pCube22_GhjostCereals_0003lambert2_0.geometry} material={materials.GhjostCereals_0003lambert2} position={[0.83, 10.5, 17.81]} rotation={[Math.PI / 2, 0, 2.09]} scale={[4.08, 5.52, 1.22]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/nerdbar-transformed.glb')
